"""
AeroGuard Pollution Forecast API Router
---------------------------------------
Endpoint: GET /api/forecast
Returns multi-step future PM2.5 and AQI forecasts generated by the trained ML pipeline.
"""

from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session
from database.connection import get_db
from backend.schemas.air_quality import ForecastResponse, ForecastPoint
from backend.services.forecast_service import get_forecast_for_location

router = APIRouter(prefix="", tags=["Forecast"])


@router.get("/forecast", response_model=ForecastResponse)
def get_pollution_forecast(
    location: str = Query("DTU, Delhi - CPCB", description="Location name"),
    hours: int = Query(12, ge=1, le=48, description="Forecast horizon in hours"),
    db: Session = Depends(get_db)
):
    """
    Returns AI-generated multi-step predictions for the upcoming hours.
    """
    res = get_forecast_for_location(db, location=location, hours_ahead=hours)
    
    forecast_points = [
        ForecastPoint(
            forecast_time=p["forecast_time"],
            hours_from_now=p["hours_from_now"],
            predicted_pm25=p["predicted_pm25"],
            predicted_pm10=p.get("predicted_pm10"),
            predicted_aqi=p["predicted_aqi"],
            category=p["category"],
            color=p["color"],
            advisory=p["advisory"]
        )
        for p in res.get("forecast", [])
    ]

    return ForecastResponse(
        location=location,
        current_pm25=res.get("current_pm25", 94.2),
        trend=res.get("trend", "Stable"),
        model_name=res.get("model_name", "Random Forest Regressor"),
        forecast=forecast_points,
        model_metrics=res.get("model_metrics", {})
    )
